site_name: PyXindy
site_url: https://yves-chevallier.github.io/pyxindy
site_author: Yves Chevallier
repo_name: yves-chevallier/pyxindy
repo_url: https://github.com/yves-chevallier/pyxindy
copyright: Copyright &copy; 2025 Yves Chevallier
nav:
  - index.md
  - Home:
      - Introduction: home/index.md
      - Features: home/features.md
      - About: home/about.md
  - Tutorial:
      - Overview: tutorial/index.md
      - Basic introduction: tutorial/basic-introduction.md
      - Advanced features: tutorial/advanced-features.md
      - About xindy: tutorial/about-xindy.md
      - References: tutorial/tutorial-references.md
  - Manual:
      - Overview: manual/index.md
      - By topic:
          - Overview: manual/by-topic/index.md
          - How-to: manual/by-topic/how-to.md
          - Practical tips: manual/by-topic/practical-tips.md
          - Errors and problems: manual/by-topic/errors-and-problems.md
          - References: manual/by-topic/by-topic-references.md
      - Manpages:
          - xindy: manual/manpages/xindy.md
          - tex2xindy: manual/manpages/tex2xindy.md
          - makeindex4: manual/manpages/makeindex4.md
      - Invoking xindy: manual/invoking-xindy.md
      - Command reference: manual/command-reference.md
      - How the index processor works: manual/how-the-index-processor-works.md
      - Processing phases: manual/processing-phases.md
      - References: manual/references.md
      - Documentation README: manual/doc-readme.md
theme:
  language: en
  name: material
  logo: assets/logo.svg
  features:
    - search
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.tracking
    - navigation.expand
    - navigation.sections
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: cyan
      accent: deep-orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: cyan
      accent: deep-orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
  - awesome-pages
  - mike:
      alias_type: redirect
  - autorefs:
      resolve_closest: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            docstring_section_style: list
            show_docstring_description: true
            show_signature_annotations: true
            docstring_style: google
            separate_signature: true
            merge_init_into_class: true
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yves-chevallier/pyxindy
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.blocks.html
  - pymdownx.blocks.caption
  - def_list
  - footnotes
  - attr_list
  - md_in_html
extra_css:
  - css/extra.css
